In [9]:
import pandas as pd

df = pd.read_csv('/Users/jeongjaeho/attic_project/testcode/data111.csv')

df

,ts,700FIC028_Y,700II781C_Y,700II782C_Y,700II783C_Y,700LI770B_Y,CUEI501_Y,CUFI008_Y,CUII503_Y,CULC501_Y,CULC508_Y,SOFC002_Y,SOFC007_Y,SORF001_Y,SWFC004_Y,SWRF001_Y,CUEI502_Y,CUEI503_Y,SWFC001_Y
0,2016-07-12 0:00,32.17403,13.226080,13.53725,13.59742,57.75349,16.92843,6.075186,100.85960,34.07219,49.91236,27.09365,3.146832,116.3690,1.040659,79.90697,16.62936,16.82737,12.874500
1,2016-07-12 0:01,32.06405,9.414404,10.28217,10.32054,57.75945,18.27904,6.050002,108.17980,34.00620,49.93046,26.90794,3.141322,116.6662,1.017292,81.33105,18.59732,18.62467,12.372010
2,2016-07-12 0:02,32.20876,9.807193,11.52965,10.00512,57.75109,17.07017,6.053713,98.98508,34.01115,49.94326,26.82659,3.142141,116.1130,0.979126,79.86474,16.93091,16.82307,12.189000
3,2016-07-12 0:03,32.17450,15.399190,15.52878,15.61818,57.75076,17.93410,6.077959,108.62690,34.02394,49.93918,26.48037,3.126388,116.5486,0.980876,77.98444,18.08318,18.33235,12.444020
4,2016-07-12 0:04,32.15032,12.643540,12.54185,12.64877,57.74354,17.36827,6.084131,98.18043,34.01924,49.90780,26.94508,3.128983,116.5777,1.020905,79.33493,17.23958,17.33637,12.916750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,2016-07-15 11:14,32.00462,15.770320,15.65841,15.71927,56.08091,18.52730,6.164919,103.92780,34.12824,49.94656,27.58762,3.179786,114.3263,0.750121,80.53542,18.19582,18.86802,9.282017
4995,2016-07-15 11:15,31.94653,11.744700,11.67167,11.71438,56.08380,17.73672,6.146446,101.41350,34.08924,49.99800,28.01667,3.186578,113.7430,0.745682,80.01757,17.39153,17.62644,9.277515
4996,2016-07-15 11:16,32.18319,10.562900,10.53658,10.70412,56.09236,18.31543,6.165348,103.18260,34.07628,49.97462,27.76990,3.188730,114.0835,0.733750,80.97989,17.94128,18.52888,9.303501
4997,2016-07-15 11:17,32.09569,16.052530,15.92344,16.98723,56.10730,18.33112,6.175298,105.15490,34.06232,50.08852,27.57987,3.200127,114.4905,0.731343,81.22403,17.82475,18.06074,9.240599
4998,2016-07-15 11:18,31.83692,14.769860,15.36486,15.67880,56.10342,17.64743,6.184599,97.93584,34.07660,50.12830,27.63685,3.178530,114.7325,0.739506,80.97850,17.30831,17.69501,9.255781

In [16]:
df2 = df['700FIC028_Y'].sample(n=500, random_state=1005)

In [17]:
df2.sort_index()

13      32.14977
18      32.20551
23      32.20430
28      32.08506
35      32.06573
          ...
4970    32.28155
4980    32.08950
4989    32.11723
4990    32.08456
4998    31.83692
Name: 700FIC028_Y, Length: 500, dtype: float64

In [19]:
feature = 'CRIM'

In [23]:
featureName = []
featureName.append(feature)
print(featureName)

['CRIM']